spring:
  datasource:
    url: jdbc:h2:file:./berlin.db
    username: berlin
    password: berlin
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        temp.use_jdbc_metadata_defaults: true
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        generate_statistics: true