spring:
  datasource:
    jdbcUrl: jdbc:h2:mem:testdb
    username: berlin
    password: berlin
  jpa:
    hibernate:
      hbm2ddl:
        auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        temp.use_jdbc_metadata_defaults: true
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        generate_statistics: true